on: [push]

jobs:
  time-install:
    name: Time install
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install colima
        run: |
          brew install docker
          colima start

      - name: Add docker image
        shell: bash
        run: sudo docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=YourStrong@Passw0rd" -p 1433:1433 --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2022-latest